const LESSON_COUNT = 75;
const TOTAL_PHRASES = 1000;
const WORDS_PER_THEME = 20;
const BASE_PHRASES_PER_THEME = Math.floor(TOTAL_PHRASES / LESSON_COUNT);
const EXTRA_PHRASES_THEMES = TOTAL_PHRASES % LESSON_COUNT;
const THEME_NAMES = Object.freeze(
  Array.from({ length: LESSON_COUNT }, (_, index) => (
    index === 0 ? "Basics" : `Lesson ${String(index + 1).padStart(2, "0")}`
  )),
);
const BASICS_WORDS_SEEDED = Object.freeze([
  { en: "hello", ua: "привіт" },
  { en: "hi", ua: "привіт" },
  { en: "name", ua: "ім'я" },
  { en: "student", ua: "студент" },
  { en: "teacher", ua: "вчитель" },
  { en: "city", ua: "місто" },
  { en: "country", ua: "країна" },
  { en: "friend", ua: "друг" },
  { en: "family", ua: "сім'я" },
  { en: "work", ua: "робота" },
  { en: "home", ua: "дім" },
  { en: "water", ua: "вода" },
  { en: "tea", ua: "чай" },
  { en: "coffee", ua: "кава" },
  { en: "book", ua: "книга" },
  { en: "pen", ua: "ручка" },
  { en: "phone", ua: "телефон" },
  { en: "table", ua: "стіл" },
  { en: "chair", ua: "стілець" },
  { en: "window", ua: "вікно" },
  { en: "door", ua: "двері" },
  { en: "day", ua: "день" },
  { en: "night", ua: "ніч" },
  { en: "morning", ua: "ранок" },
  { en: "evening", ua: "вечір" },
]);
const BASICS_PHRASES_SEEDED = Object.freeze([
  { en: "My name is ...", ua: "Мене звати ..." },
  { en: "I am from Ukraine.", ua: "Я з України." },
  { en: "I live in Kyiv.", ua: "Я живу в Києві." },
  { en: "I am a student.", ua: "Я студент." },
  { en: "I am a teacher.", ua: "Я вчитель." },
  { en: "How are you?", ua: "Як справи?" },
  { en: "I am fine, thank you.", ua: "Я добре, дякую." },
  { en: "Nice to meet you.", ua: "Приємно познайомитися." },
  { en: "Nice to meet you too.", ua: "Мені також приємно познайомитися." },
  { en: "What is your name?", ua: "Як тебе звати?" },
  { en: "Where are you from?", ua: "Звідки ти?" },
  { en: "I speak a little English.", ua: "Я трохи говорю англійською." },
  { en: "Please speak slowly.", ua: "Будь ласка, говори повільно." },
  { en: "Can you help me?", ua: "Ти можеш мені допомогти?" },
  { en: "I do not understand.", ua: "Я не розумію." },
]);

const COMMON_WORD_POOL = Object.freeze([
  { en: "hello", ua: "привіт" }, { en: "thank you", ua: "дякую" }, { en: "please", ua: "будь ласка" },
  { en: "sorry", ua: "вибач" }, { en: "yes", ua: "так" }, { en: "no", ua: "ні" },
  { en: "name", ua: "ім'я" }, { en: "family", ua: "сім'я" }, { en: "friend", ua: "друг" },
  { en: "work", ua: "робота" }, { en: "job", ua: "професія" }, { en: "office", ua: "офіс" },
  { en: "home", ua: "дім" }, { en: "room", ua: "кімната" }, { en: "street", ua: "вулиця" },
  { en: "city", ua: "місто" }, { en: "country", ua: "країна" }, { en: "travel", ua: "подорож" },
  { en: "ticket", ua: "квиток" }, { en: "station", ua: "станція" }, { en: "airport", ua: "аеропорт" },
  { en: "hotel", ua: "готель" }, { en: "restaurant", ua: "ресторан" }, { en: "menu", ua: "меню" },
  { en: "water", ua: "вода" }, { en: "tea", ua: "чай" }, { en: "coffee", ua: "кава" },
  { en: "bread", ua: "хліб" }, { en: "breakfast", ua: "сніданок" }, { en: "lunch", ua: "обід" },
  { en: "dinner", ua: "вечеря" }, { en: "time", ua: "час" }, { en: "morning", ua: "ранок" },
  { en: "evening", ua: "вечір" }, { en: "today", ua: "сьогодні" }, { en: "tomorrow", ua: "завтра" },
  { en: "week", ua: "тиждень" }, { en: "month", ua: "місяць" }, { en: "year", ua: "рік" },
  { en: "book", ua: "книга" }, { en: "pen", ua: "ручка" }, { en: "phone", ua: "телефон" },
  { en: "computer", ua: "комп'ютер" }, { en: "question", ua: "питання" }, { en: "answer", ua: "відповідь" },
  { en: "lesson", ua: "урок" }, { en: "word", ua: "слово" }, { en: "phrase", ua: "фраза" },
  { en: "easy", ua: "легкий" }, { en: "difficult", ua: "складний" }, { en: "correct", ua: "правильний" },
  { en: "important", ua: "важливий" }, { en: "happy", ua: "щасливий" }, { en: "tired", ua: "втомлений" },
  { en: "busy", ua: "зайнятий" }, { en: "free", ua: "вільний" }, { en: "open", ua: "відкритий" },
  { en: "close", ua: "закривати / близько" }, { en: "buy", ua: "купувати" }, { en: "sell", ua: "продавати" },
  { en: "help", ua: "допомога" }, { en: "understand", ua: "розуміти" }, { en: "speak", ua: "говорити" },
  { en: "listen", ua: "слухати" }, { en: "read", ua: "читати" }, { en: "write", ua: "писати" },
  { en: "learn", ua: "вивчати" }, { en: "study", ua: "навчатися" }, { en: "repeat", ua: "повторювати" },
  { en: "practice", ua: "практикувати" }, { en: "start", ua: "починати" }, { en: "finish", ua: "завершувати" },
]);

const COMMON_PHRASE_POOL = Object.freeze([
  { en: "Hello! How are you?", ua: "Привіт! Як справи?" },
  { en: "I am fine, thank you.", ua: "Я добре, дякую." },
  { en: "What is your name?", ua: "Як тебе звати?" },
  { en: "My name is ...", ua: "Мене звати ..." },
  { en: "Nice to meet you.", ua: "Приємно познайомитися." },
  { en: "Where are you from?", ua: "Звідки ти?" },
  { en: "I am from Ukraine.", ua: "Я з України." },
  { en: "I live in Kyiv.", ua: "Я живу в Києві." },
  { en: "Can you help me, please?", ua: "Можеш допомогти мені, будь ласка?" },
  { en: "I do not understand.", ua: "Я не розумію." },
  { en: "Please speak slowly.", ua: "Будь ласка, говори повільно." },
  { en: "How much is it?", ua: "Скільки це коштує?" },
  { en: "I would like coffee, please.", ua: "Я б хотів каву, будь ласка." },
  { en: "Can I have the menu?", ua: "Можна меню?" },
  { en: "Could I have the bill?", ua: "Можна рахунок?" },
  { en: "What time is it now?", ua: "Котра зараз година?" },
  { en: "I am busy today.", ua: "Я сьогодні зайнятий." },
  { en: "I am free tomorrow.", ua: "Я вільний завтра." },
  { en: "Let us meet in the evening.", ua: "Давай зустрінемось ввечері." },
  { en: "I go to work at nine.", ua: "Я йду на роботу о дев'ятій." },
  { en: "My family is very friendly.", ua: "Моя сім'я дуже дружня." },
  { en: "I have a brother and a sister.", ua: "У мене є брат і сестра." },
  { en: "We study English every day.", ua: "Ми вивчаємо англійську щодня." },
  { en: "This lesson is very useful.", ua: "Цей урок дуже корисний." },
  { en: "Please repeat this phrase.", ua: "Будь ласка, повтори цю фразу." },
  { en: "I want to practice more.", ua: "Я хочу більше практикувати." },
  { en: "Can you write it for me?", ua: "Можеш написати це для мене?" },
  { en: "I can read this text.", ua: "Я можу читати цей текст." },
  { en: "I can speak a little English.", ua: "Я трохи говорю англійською." },
  { en: "Thank you for your help.", ua: "Дякую за твою допомогу." },
  { en: "You are welcome.", ua: "Будь ласка (нема за що)." },
  { en: "See you tomorrow!", ua: "Побачимось завтра!" },
  { en: "Have a nice day!", ua: "Гарного дня!" },
  { en: "Good luck with your lesson!", ua: "Успіхів з уроком!" },
]);

const EARLY_LESSON_OVERRIDES = Object.freeze({
  "Basics": {
    words: BASICS_WORDS_SEEDED,
    phrases: BASICS_PHRASES_SEEDED,
    material: [
      "Урок 1. Знайомство (book-style)",
        "[IMG:lesson-01-intro.svg]",
      "  O/  Hello!",
      " /|   My name is Anna.",
      " / \\",
      "",
      "Ситуація: ти знайомишся з людиною вперше.",
      "Діалог:",
      "- Hello! My name is Anna. (Привіт! Мене звати Анна.)",
      "- Hi! I am Mark. Nice to meet you. (Привіт! Я Марк. Приємно познайомитися.)",
      "",
      "Граматика: I am = I'm.",
      "Вимова: th у thanks - язик між зубами.",
      "Міні-завдання: скажи 2 фрази про себе англійською.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Привіт! Мене звати Олексій.",
      expectedAnswers: ["hello my name is *", "hi my name is *"],
      explanationUa: "Використай шаблон: Hello/Hi, my name is ...",
    },
  },
  "Lesson 02": {
    words: [
      { en: "country", ua: "країна" },
      { en: "city", ua: "місто" },
      { en: "from", ua: "з (звідки)" },
      { en: "live", ua: "жити" },
      { en: "address", ua: "адреса" },
      { en: "street", ua: "вулиця" },
      { en: "house", ua: "будинок" },
      { en: "flat", ua: "квартира" },
      { en: "district", ua: "район" },
      { en: "neighborhood", ua: "околиці / район проживання" },
      { en: "postcode", ua: "поштовий індекс" },
      { en: "capital", ua: "столиця" },
      { en: "map", ua: "мапа" },
      { en: "travel", ua: "подорожувати" },
      { en: "visit", ua: "відвідувати" },
      { en: "near", ua: "поруч" },
      { en: "region", ua: "регіон" },
      { en: "town", ua: "містечко" },
      { en: "village", ua: "село" },
      { en: "abroad", ua: "за кордоном" },
    ],
    phrases: [
      { en: "Where are you from?", ua: "Звідки ти?" },
      { en: "I am from Ukraine.", ua: "Я з України." },
      { en: "I live in Kyiv.", ua: "Я живу в Києві." },
      { en: "What is your address?", ua: "Яка твоя адреса?" },
      { en: "My street is Shevchenko Street.", ua: "Моя вулиця - вулиця Шевченка." },
      { en: "I live near the city center.", ua: "Я живу біля центру міста." },
      { en: "Kyiv is the capital of Ukraine.", ua: "Київ - столиця України." },
      { en: "Can you show it on the map?", ua: "Можеш показати це на мапі?" },
      { en: "I want to visit London.", ua: "Я хочу відвідати Лондон." },
      { en: "My postcode is 01001.", ua: "Мій поштовий індекс 01001." },
      { en: "I am from a small town.", ua: "Я з маленького містечка." },
      { en: "Where do you live now?", ua: "Де ти живеш зараз?" },
      { en: "I live abroad now.", ua: "Я зараз живу за кордоном." },
      { en: "Is your city big?", ua: "Твоє місто велике?" },
    ],
    material: [
      "Урок 2. Звідки ти?",
        "[IMG:lesson-02-from.svg]",
      "  _______      ____",
      " | UKRAINE| -> |KYIV|",
      "  -------      ----",
      "",
      "Ситуація: коротка розмова про країну і місто.",
      "Діалог:",
      "- Where are you from? (Звідки ти?)",
      "- I am from Ukraine. I live in Kyiv. (Я з України. Я живу в Києві.)",
      "",
      "Граматика: from + country, live in + city.",
      "Міні-завдання: відповідай на питання 'Where are you from?'",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Я з України. Я живу в Києві.",
      expectedAnswers: ["i am from ukraine i live in kyiv", "i'm from ukraine i live in kyiv"],
      explanationUa: "Шаблон: I am from ..., I live in ...",
    },
  },
  "Lesson 03": {
    words: [
      { en: "family", ua: "сім'я" },
      { en: "mother", ua: "мама" },
      { en: "father", ua: "тато" },
      { en: "brother", ua: "брат" },
      { en: "sister", ua: "сестра" },
      { en: "son", ua: "син" },
      { en: "daughter", ua: "донька" },
      { en: "married", ua: "одружений/заміжня" },
      { en: "parents", ua: "батьки" },
      { en: "grandmother", ua: "бабуся" },
      { en: "grandfather", ua: "дідусь" },
      { en: "uncle", ua: "дядько" },
      { en: "aunt", ua: "тітка" },
      { en: "cousin", ua: "двоюрідний брат / сестра" },
      { en: "child", ua: "дитина" },
      { en: "children", ua: "діти" },
      { en: "husband", ua: "чоловік (у шлюбі)" },
      { en: "wife", ua: "дружина" },
      { en: "single", ua: "неодружений / незаміжня" },
      { en: "relative", ua: "родич" },
    ],
    phrases: [
      { en: "This is my family.", ua: "Це моя сім'я." },
      { en: "I have a brother.", ua: "У мене є брат." },
      { en: "My mother is a teacher.", ua: "Моя мама вчитель." },
      { en: "My father works in an office.", ua: "Мій тато працює в офісі." },
      { en: "I have two children.", ua: "У мене двоє дітей." },
      { en: "My sister is married.", ua: "Моя сестра заміжня." },
      { en: "My parents live in Lviv.", ua: "Мої батьки живуть у Львові." },
      { en: "My grandmother is very kind.", ua: "Моя бабуся дуже добра." },
      { en: "We visit our relatives on weekends.", ua: "Ми відвідуємо родичів на вихідних." },
      { en: "Do you have a big family?", ua: "У тебе велика сім'я?" },
      { en: "My family is friendly.", ua: "Моя сім'я дружня." },
      { en: "I have one son and one daughter.", ua: "У мене один син і одна донька." },
      { en: "My uncle lives abroad.", ua: "Мій дядько живе за кордоном." },
      { en: "We are a close family.", ua: "Ми дружна (тісна) сім'я." },
    ],
    material: [
      "Урок 3. Сім'я",
        "[IMG:lesson-03-family.svg]",
      "   O   O",
      "  /|\\ /|\\   <- parents",
      "   |   |",
      "  / \\ / \\",
      "",
      "Ситуація: коротко розказуєш про сім'ю.",
      "Граматика: have/has для складу сім'ї.",
      "Міні-завдання: скажи 2 речення про свою сім'ю.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Це моя сім'я. У мене є сестра.",
      expectedAnswers: ["this is my family i have a sister"],
      explanationUa: "Використай структуру: This is..., I have...",
    },
  },
  "Lesson 04": {
    words: [
      { en: "morning", ua: "ранок" },
      { en: "evening", ua: "вечір" },
      { en: "today", ua: "сьогодні" },
      { en: "tomorrow", ua: "завтра" },
      { en: "busy", ua: "зайнятий" },
      { en: "free", ua: "вільний" },
      { en: "meet", ua: "зустрічатися" },
      { en: "time", ua: "час" },
      { en: "afternoon", ua: "день (після обіду)" },
      { en: "night", ua: "ніч" },
      { en: "early", ua: "рано" },
      { en: "late", ua: "пізно" },
      { en: "schedule", ua: "розклад" },
      { en: "appointment", ua: "зустріч / запис" },
      { en: "weekend", ua: "вихідні" },
      { en: "clock", ua: "годинник" },
      { en: "minute", ua: "хвилина" },
      { en: "hour", ua: "година" },
      { en: "calendar", ua: "календар" },
      { en: "plan", ua: "план" },
    ],
    phrases: [
      { en: "Good morning!", ua: "Доброго ранку!" },
      { en: "Are you free today?", ua: "Ти вільний сьогодні?" },
      { en: "I am busy now.", ua: "Я зараз зайнятий." },
      { en: "Let's meet tomorrow.", ua: "Давай зустрінемось завтра." },
      { en: "What time is it?", ua: "Котра година?" },
      { en: "It is five o'clock.", ua: "П'ята година." },
      { en: "I have an appointment at ten.", ua: "У мене зустріч о десятій." },
      { en: "I wake up early.", ua: "Я прокидаюся рано." },
      { en: "I go to bed late.", ua: "Я лягаю спати пізно." },
      { en: "Are you free this weekend?", ua: "Ти вільний цими вихідними?" },
      { en: "What time do you wake up?", ua: "О котрій ти прокидаєшся?" },
      { en: "I start work at nine.", ua: "Я починаю роботу о дев'ятій." },
      { en: "Let's meet at half past six.", ua: "Давай зустрінемось о пів на сьому." },
      { en: "See you tomorrow morning.", ua: "Побачимось завтра зранку." },
    ],
    material: [
      "Урок 4. Час і плани",
        "[IMG:lesson-04-time.svg]",
      "  08:00 -> morning",
      "  19:00 -> evening",
      "",
      "Ситуація: домовляєшся про зустріч.",
      "Граматика: now/today/tomorrow.",
      "Міні-завдання: склади 2 фрази про свої плани.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Ти вільний сьогодні? Я зайнятий зараз.",
      expectedAnswers: ["are you free today i am busy now"],
      explanationUa: "Використай free/busy і today/now.",
    },
  },
  "Lesson 05": {
    words: [
      { en: "water", ua: "вода" },
      { en: "tea", ua: "чай" },
      { en: "coffee", ua: "кава" },
      { en: "bread", ua: "хліб" },
      { en: "menu", ua: "меню" },
      { en: "bill", ua: "рахунок" },
      { en: "table", ua: "стіл" },
      { en: "waiter", ua: "офіціант" },
      { en: "breakfast", ua: "сніданок" },
      { en: "lunch", ua: "обід" },
      { en: "dinner", ua: "вечеря" },
      { en: "soup", ua: "суп" },
      { en: "salad", ua: "салат" },
      { en: "chicken", ua: "курка" },
      { en: "juice", ua: "сік" },
      { en: "dessert", ua: "десерт" },
      { en: "order", ua: "замовлення / замовляти" },
      { en: "fork", ua: "виделка" },
      { en: "knife", ua: "ніж" },
      { en: "plate", ua: "тарілка" },
    ],
    phrases: [
      { en: "I would like tea, please.", ua: "Я б хотів чай, будь ласка." },
      { en: "Can I have the menu?", ua: "Можна меню?" },
      { en: "A table for two, please.", ua: "Стіл на двох, будь ласка." },
      { en: "Could I have the bill?", ua: "Можна рахунок?" },
      { en: "I would like chicken soup.", ua: "Я б хотів курячий суп." },
      { en: "Can I have a salad?", ua: "Можна салат?" },
      { en: "Do you have dessert?", ua: "У вас є десерт?" },
      { en: "I will take orange juice.", ua: "Я візьму апельсиновий сік." },
      { en: "The food is very tasty.", ua: "Їжа дуже смачна." },
      { en: "Can we pay by card?", ua: "Можна оплатити карткою?" },
      { en: "Can I order now?", ua: "Можна замовити зараз?" },
      { en: "I would like a table near the window.", ua: "Я б хотів стіл біля вікна." },
      { en: "The bill, please.", ua: "Рахунок, будь ласка." },
      { en: "Everything was great, thank you.", ua: "Все було чудово, дякую." },
    ],
    material: [
      "Урок 5. У кафе",
        "[IMG:lesson-05-cafe.svg]",
      "  _________",
      " | TEA  COFFEE |",
      " |___MENU_____|",
      "",
      "Ситуація: замовлення у кафе.",
      "Діалог:",
      "- Can I have the menu? (Можна меню?)",
      "- I would like tea, please. (Я б хотів чай, будь ласка.)",
      "",
      "Граматика: I would like ...",
      "Міні-завдання: зроби власне замовлення 1 фразою.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Я б хотів каву, будь ласка.",
      expectedAnswers: ["i would like coffee please"],
      explanationUa: "Формула ввічливого замовлення: I would like ...",
    },
  },
  "Lesson 06": {
    words: [
      { en: "bus", ua: "автобус" }, { en: "stop", ua: "зупинка" }, { en: "metro", ua: "метро" },
      { en: "train", ua: "потяг" }, { en: "platform", ua: "платформа" }, { en: "route", ua: "маршрут" },
      { en: "ticket", ua: "квиток" }, { en: "station", ua: "станція" }, { en: "driver", ua: "водій" },
      { en: "passenger", ua: "пасажир" }, { en: "map", ua: "мапа" }, { en: "transfer", ua: "пересадка" },
    ],
    phrases: [
      { en: "Where is the bus stop?", ua: "Де автобусна зупинка?" },
      { en: "I need a ticket to the center.", ua: "Мені потрібен квиток до центру." },
      { en: "Which metro line should I take?", ua: "Яку лінію метро мені обрати?" },
      { en: "Is this seat free?", ua: "Це місце вільне?" },
      { en: "I have one transfer.", ua: "У мене одна пересадка." },
      { en: "This train is late.", ua: "Цей потяг запізнюється." },
      { en: "How many stops are left?", ua: "Скільки зупинок залишилось?" },
      { en: "Please tell me when to get off.", ua: "Скажіть, будь ласка, коли мені виходити." },
      { en: "The station is near the museum.", ua: "Станція біля музею." },
      { en: "Can I pay by card?", ua: "Можна оплатити карткою?" },
      { en: "We are on the right route.", ua: "Ми на правильному маршруті." },
      { en: "Let us check the map.", ua: "Давай перевіримо мапу." },
      { en: "The bus is crowded.", ua: "Автобус переповнений." },
      { en: "I will take the next train.", ua: "Я поїду наступним потягом." },
    ],
    material: [
      "Урок 6. Транспорт у місті",
      "[IMG:lesson-02-from.svg]",
      "Вступ: орієнтуємося в автобусі, метро і на станції.",
      "Міні-діалог:",
      "- Where is the bus stop? (Де автобусна зупинка?)",
      "- It is near the metro station. (Вона біля станції метро.)",
      "Теорія: питання з Where/Which/How many.",
      "Граматика: should + verb для поради маршруту.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Де автобусна зупинка? Мені потрібен квиток.",
      expectedAnswers: ["where is the bus stop i need a ticket"],
      explanationUa: "Використай Where is ...? і I need ...",
    },
  },
  "Lesson 07": {
    words: [
      { en: "shop", ua: "магазин" }, { en: "price", ua: "ціна" }, { en: "discount", ua: "знижка" },
      { en: "size", ua: "розмір" }, { en: "color", ua: "колір" }, { en: "cash", ua: "готівка" },
      { en: "card", ua: "картка" }, { en: "receipt", ua: "чек" }, { en: "change", ua: "решта" },
      { en: "try on", ua: "приміряти" }, { en: "customer", ua: "клієнт" }, { en: "seller", ua: "продавець" },
    ],
    phrases: [
      { en: "How much is this shirt?", ua: "Скільки коштує ця сорочка?" },
      { en: "Do you have this in blue?", ua: "У вас є це в синьому кольорі?" },
      { en: "Can I try it on?", ua: "Можна приміряти?" },
      { en: "I need a bigger size.", ua: "Мені потрібен більший розмір." },
      { en: "Is there any discount?", ua: "Є якась знижка?" },
      { en: "I will pay by card.", ua: "Я оплачу карткою." },
      { en: "Can I have the receipt?", ua: "Можна чек?" },
      { en: "Keep the change.", ua: "Решту залиште собі." },
      { en: "This is too expensive.", ua: "Це занадто дорого." },
      { en: "I like this color.", ua: "Мені подобається цей колір." },
      { en: "Where is the fitting room?", ua: "Де примірочна?" },
      { en: "I am just looking, thank you.", ua: "Я просто дивлюся, дякую." },
      { en: "Can you help me choose?", ua: "Можете допомогти мені обрати?" },
      { en: "I will take it.", ua: "Я це беру." },
    ],
    material: [
      "Урок 7. Покупки",
      "[IMG:lesson-05-cafe.svg]",
      "Вступ: розмова з продавцем у магазині.",
      "Міні-діалог:",
      "- Can I try it on? (Можна приміряти?)",
      "- Yes, the fitting room is over there. (Так, примірочна там.)",
      "Теорія: ввічливі запити з Can I ...?",
      "Граматика: this/that, bigger/smaller.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Скільки це коштує? Можна чек?",
      expectedAnswers: ["how much is it can i have the receipt"],
      explanationUa: "Комбінуй питання про ціну та оплату.",
    },
  },
  "Lesson 08": {
    words: [
      { en: "job", ua: "робота" }, { en: "office", ua: "офіс" }, { en: "meeting", ua: "зустріч" },
      { en: "task", ua: "завдання" }, { en: "project", ua: "проєкт" }, { en: "deadline", ua: "дедлайн" },
      { en: "manager", ua: "менеджер" }, { en: "colleague", ua: "колега" }, { en: "email", ua: "електронний лист" },
      { en: "report", ua: "звіт" }, { en: "schedule", ua: "розклад" }, { en: "break", ua: "перерва" },
    ],
    phrases: [
      { en: "I work in an office.", ua: "Я працюю в офісі." },
      { en: "We have a meeting at ten.", ua: "У нас зустріч о десятій." },
      { en: "This task is important.", ua: "Це завдання важливе." },
      { en: "The deadline is tomorrow.", ua: "Дедлайн завтра." },
      { en: "Please send me an email.", ua: "Будь ласка, надішли мені лист." },
      { en: "I need to finish the report.", ua: "Мені треба завершити звіт." },
      { en: "My manager is very helpful.", ua: "Мій менеджер дуже допомагає." },
      { en: "I have a short break now.", ua: "У мене зараз коротка перерва." },
      { en: "Can we change the schedule?", ua: "Можемо змінити розклад?" },
      { en: "I work from home today.", ua: "Я працюю з дому сьогодні." },
      { en: "Let us discuss the project.", ua: "Давай обговоримо проєкт." },
      { en: "My colleague is on vacation.", ua: "Мій колега у відпустці." },
      { en: "I am busy this afternoon.", ua: "Я зайнятий сьогодні після обіду." },
      { en: "We can talk later.", ua: "Ми можемо поговорити пізніше." },
    ],
    material: [
      "Урок 8. Робочий день",
      "[IMG:lesson-04-time.svg]",
      "Вступ: базова офісна розмова.",
      "Міні-діалог:",
      "- We have a meeting at ten. (У нас зустріч о десятій.)",
      "- Okay, I will prepare the report. (Добре, я підготую звіт.)",
      "Теорія: частотні дієслова в робочому контексті.",
      "Граматика: Present Simple для рутини.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: У нас зустріч о десятій. Дедлайн завтра.",
      expectedAnswers: ["we have a meeting at ten the deadline is tomorrow"],
      explanationUa: "Опиши робочу ситуацію двома простими реченнями.",
    },
  },
  "Lesson 09": {
    words: [
      { en: "doctor", ua: "лікар" }, { en: "patient", ua: "пацієнт" }, { en: "hospital", ua: "лікарня" },
      { en: "clinic", ua: "клініка" }, { en: "pain", ua: "біль" }, { en: "fever", ua: "температура" },
      { en: "headache", ua: "головний біль" }, { en: "medicine", ua: "ліки" }, { en: "pharmacy", ua: "аптека" },
      { en: "appointment", ua: "прийом" }, { en: "health", ua: "здоров'я" }, { en: "rest", ua: "відпочинок" },
    ],
    phrases: [
      { en: "I do not feel well.", ua: "Я почуваюся недобре." },
      { en: "I have a headache.", ua: "У мене болить голова." },
      { en: "I need to see a doctor.", ua: "Мені потрібно до лікаря." },
      { en: "Do you have a fever?", ua: "У вас є температура?" },
      { en: "Please take this medicine.", ua: "Будь ласка, приймайте ці ліки." },
      { en: "You need more rest.", ua: "Вам потрібно більше відпочинку." },
      { en: "The pharmacy is nearby.", ua: "Аптека поруч." },
      { en: "I have an appointment at noon.", ua: "У мене запис на прийом опівдні." },
      { en: "Drink more water.", ua: "Пийте більше води." },
      { en: "My health is better now.", ua: "Моє здоров'я зараз краще." },
      { en: "Can you help me, please?", ua: "Можете допомогти, будь ласка?" },
      { en: "I feel tired and weak.", ua: "Я почуваюся втомлено і слабко." },
      { en: "I will stay at home today.", ua: "Я залишуся вдома сьогодні." },
      { en: "Thank you, doctor.", ua: "Дякую, лікарю." },
    ],
    material: [
      "Урок 9. У лікаря",
      "[IMG:lesson-03-family.svg]",
      "Вступ: як описати самопочуття і звернутися по допомогу.",
      "Міні-діалог:",
      "- I have a headache. (У мене болить голова.)",
      "- Please rest and take medicine. (Будь ласка, відпочиньте і прийміть ліки.)",
      "Теорія: конструкції I have ... / I feel ...",
      "Граматика: модальне should для порад.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Я почуваюся недобре. Мені потрібно до лікаря.",
      expectedAnswers: ["i do not feel well i need to see a doctor"],
      explanationUa: "Використай дві базові фрази про здоров'я.",
    },
  },
  "Lesson 10": {
    words: [
      { en: "weather", ua: "погода" }, { en: "sunny", ua: "сонячно" }, { en: "cloudy", ua: "хмарно" },
      { en: "rainy", ua: "дощово" }, { en: "windy", ua: "вітряно" }, { en: "cold", ua: "холодно" },
      { en: "warm", ua: "тепло" }, { en: "hot", ua: "спекотно" }, { en: "forecast", ua: "прогноз" },
      { en: "umbrella", ua: "парасолька" }, { en: "jacket", ua: "куртка" }, { en: "season", ua: "пора року" },
    ],
    phrases: [
      { en: "What is the weather like today?", ua: "Яка сьогодні погода?" },
      { en: "It is sunny and warm.", ua: "Сонячно і тепло." },
      { en: "It is cold outside.", ua: "Надворі холодно." },
      { en: "Take your umbrella.", ua: "Візьми парасольку." },
      { en: "The forecast says rain.", ua: "Прогноз каже, що буде дощ." },
      { en: "It is very windy today.", ua: "Сьогодні дуже вітряно." },
      { en: "I need a warm jacket.", ua: "Мені потрібна тепла куртка." },
      { en: "Spring is my favorite season.", ua: "Весна - моя улюблена пора року." },
      { en: "The sky is cloudy.", ua: "Небо хмарне." },
      { en: "It will be hot tomorrow.", ua: "Завтра буде спекотно." },
      { en: "I like rainy weather.", ua: "Мені подобається дощова погода." },
      { en: "Do not forget your scarf.", ua: "Не забудь свій шарф." },
      { en: "Let us stay inside today.", ua: "Давай залишимось сьогодні вдома." },
      { en: "The weather changes quickly.", ua: "Погода швидко змінюється." },
    ],
    material: [
      "Урок 10. Погода",
      "[IMG:lesson-04-time.svg]",
      "Вступ: опис погоди в повсякденній розмові.",
      "Міні-діалог:",
      "- What is the weather like today? (Яка сьогодні погода?)",
      "- It is rainy, take an umbrella. (Дощово, візьми парасольку.)",
      "Теорія: прикметники погоди + It is ...",
      "Граматика: майбутнє з will для прогнозу.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Сьогодні вітряно. Візьми парасольку.",
      expectedAnswers: ["it is windy today take your umbrella"],
      explanationUa: "Опиши погоду і коротку пораду.",
    },
  },
  "Lesson 11": {
    words: [
      { en: "hobby", ua: "хобі" }, { en: "music", ua: "музика" }, { en: "movie", ua: "фільм" },
      { en: "book", ua: "книга" }, { en: "sport", ua: "спорт" }, { en: "run", ua: "бігати" },
      { en: "swim", ua: "плавати" }, { en: "paint", ua: "малювати" }, { en: "game", ua: "гра" },
      { en: "weekend", ua: "вихідні" }, { en: "fun", ua: "весело" }, { en: "relax", ua: "відпочивати" },
    ],
    phrases: [
      { en: "My hobby is reading.", ua: "Моє хобі - читання." },
      { en: "I like listening to music.", ua: "Я люблю слухати музику." },
      { en: "Do you play any sport?", ua: "Ти займаєшся спортом?" },
      { en: "I run in the park.", ua: "Я бігаю в парку." },
      { en: "I swim on weekends.", ua: "Я плаваю у вихідні." },
      { en: "Let us watch a movie tonight.", ua: "Давай подивимось фільм сьогодні ввечері." },
      { en: "This game is very fun.", ua: "Ця гра дуже весела." },
      { en: "I paint in my free time.", ua: "Я малюю у вільний час." },
      { en: "We can relax at home.", ua: "Ми можемо відпочити вдома." },
      { en: "Reading helps me learn.", ua: "Читання допомагає мені вчитися." },
      { en: "What do you do for fun?", ua: "Що ти робиш для задоволення?" },
      { en: "I enjoy long walks.", ua: "Мені подобаються довгі прогулянки." },
      { en: "Let us play together.", ua: "Давай пограємо разом." },
      { en: "I need more practice.", ua: "Мені потрібно більше практики." },
    ],
    material: [
      "Урок 11. Хобі та вільний час",
      "[IMG:lesson-01-intro.svg]",
      "Вступ: говоримо про те, що любимо робити після роботи/навчання.",
      "Міні-діалог:",
      "- What do you do for fun? (Що ти робиш для задоволення?)",
      "- I read books and listen to music. (Я читаю книги і слухаю музику.)",
      "Теорія: like/enjoy + gerund (reading, listening).",
      "Граматика: Present Simple для звичок.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Моє хобі - читання. Я люблю музику.",
      expectedAnswers: ["my hobby is reading i like music", "my hobby is reading i like listening to music"],
      explanationUa: "Скажи про хобі двома короткими реченнями.",
    },
  },
  "Lesson 12": {
    words: [
      { en: "study", ua: "навчання" }, { en: "teacher", ua: "вчитель" }, { en: "student", ua: "студент" },
      { en: "class", ua: "заняття" }, { en: "homework", ua: "домашнє завдання" }, { en: "exam", ua: "іспит" },
      { en: "exercise", ua: "вправа" }, { en: "rule", ua: "правило" }, { en: "grammar", ua: "граматика" },
      { en: "vocabulary", ua: "словниковий запас" }, { en: "mistake", ua: "помилка" }, { en: "result", ua: "результат" },
    ],
    phrases: [
      { en: "I study English every day.", ua: "Я вивчаю англійську щодня." },
      { en: "Our teacher is very kind.", ua: "Наш вчитель дуже добрий." },
      { en: "We have class at eight.", ua: "У нас заняття о восьмій." },
      { en: "I need to do my homework.", ua: "Мені треба зробити домашнє завдання." },
      { en: "This grammar rule is important.", ua: "Це граматичне правило важливе." },
      { en: "I made a small mistake.", ua: "Я зробив невелику помилку." },
      { en: "My exam is next week.", ua: "Мій іспит наступного тижня." },
      { en: "Please check my exercise.", ua: "Будь ласка, перевір мою вправу." },
      { en: "I want to improve my vocabulary.", ua: "Я хочу покращити свій словниковий запас." },
      { en: "My result is better now.", ua: "Мій результат зараз кращий." },
      { en: "Can you explain this rule?", ua: "Можеш пояснити це правило?" },
      { en: "Let us repeat the lesson.", ua: "Давай повторимо урок." },
      { en: "I understand this topic now.", ua: "Я тепер розумію цю тему." },
      { en: "Practice makes progress.", ua: "Практика дає прогрес." },
    ],
    material: [
      "Урок 12. Навчання",
      "[IMG:lesson-03-family.svg]",
      "Вступ: навчальна лексика для щоденної практики.",
      "Міні-діалог:",
      "- Did you do your homework? (Ти зробив домашнє завдання?)",
      "- Yes, but I have one mistake. (Так, але маю одну помилку.)",
      "Теорія: навчальні дієслова do/check/repeat/improve.",
      "Граматика: Present/Past у простих навчальних фразах.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Я вивчаю англійську щодня. Це правило важливе.",
      expectedAnswers: ["i study english every day this rule is important"],
      explanationUa: "Поєднай твердження про навчання і правило.",
    },
  },
  "Lesson 13": {
    words: [
      { en: "home", ua: "дім" }, { en: "kitchen", ua: "кухня" }, { en: "bedroom", ua: "спальня" },
      { en: "bathroom", ua: "ванна кімната" }, { en: "living room", ua: "вітальня" }, { en: "clean", ua: "чистити" },
      { en: "cook", ua: "готувати" }, { en: "wash", ua: "мити" }, { en: "floor", ua: "підлога" },
      { en: "window", ua: "вікно" }, { en: "door", ua: "двері" }, { en: "garden", ua: "сад" },
    ],
    phrases: [
      { en: "I am at home now.", ua: "Я зараз вдома." },
      { en: "The kitchen is clean.", ua: "Кухня чиста." },
      { en: "I cook dinner every evening.", ua: "Я готую вечерю щовечора." },
      { en: "Please wash the dishes.", ua: "Будь ласка, помий посуд." },
      { en: "My bedroom is small but cozy.", ua: "Моя спальня маленька, але затишна." },
      { en: "Open the window, please.", ua: "Відкрий вікно, будь ласка." },
      { en: "Close the door, please.", ua: "Закрий двері, будь ласка." },
      { en: "We have a small garden.", ua: "У нас є маленький сад." },
      { en: "I clean the floor on Saturday.", ua: "Я мию підлогу у суботу." },
      { en: "The living room is bright.", ua: "Вітальня світла." },
      { en: "Can you help me in the kitchen?", ua: "Можеш допомогти мені на кухні?" },
      { en: "I like my home.", ua: "Мені подобається мій дім." },
      { en: "Everything is ready.", ua: "Все готово." },
      { en: "Let us tidy the room.", ua: "Давай приберемо кімнату." },
    ],
    material: [
      "Урок 13. Дім і побут",
      "[IMG:lesson-05-cafe.svg]",
      "Вступ: щоденні домашні дії та кімнати.",
      "Міні-діалог:",
      "- Can you help me in the kitchen? (Можеш допомогти мені на кухні?)",
      "- Sure, I will wash the dishes. (Звісно, я помию посуд.)",
      "Теорія: дії вдома в Present Simple.",
      "Граматика: імператив (Open/Close/Wash).",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Кухня чиста. Будь ласка, закрий двері.",
      expectedAnswers: ["the kitchen is clean please close the door"],
      explanationUa: "Комбінуй опис стану і коротке прохання.",
    },
  },
  "Lesson 14": {
    words: [
      { en: "week", ua: "тиждень" }, { en: "monday", ua: "понеділок" }, { en: "tuesday", ua: "вівторок" },
      { en: "wednesday", ua: "середа" }, { en: "thursday", ua: "четвер" }, { en: "friday", ua: "п'ятниця" },
      { en: "saturday", ua: "субота" }, { en: "sunday", ua: "неділя" }, { en: "plan", ua: "план" },
      { en: "calendar", ua: "календар" }, { en: "event", ua: "подія" }, { en: "holiday", ua: "свято" },
    ],
    phrases: [
      { en: "Today is Monday.", ua: "Сьогодні понеділок." },
      { en: "I work from Monday to Friday.", ua: "Я працюю з понеділка по п'ятницю." },
      { en: "We rest on Saturday and Sunday.", ua: "Ми відпочиваємо у суботу та неділю." },
      { en: "What are your plans this week?", ua: "Які твої плани на цей тиждень?" },
      { en: "I have an event on Thursday.", ua: "У мене подія в четвер." },
      { en: "Let us check the calendar.", ua: "Давай перевіримо календар." },
      { en: "Friday is a busy day.", ua: "П'ятниця - насичений день." },
      { en: "Sunday is my favorite day.", ua: "Неділя - мій улюблений день." },
      { en: "We have a holiday next week.", ua: "У нас свято наступного тижня." },
      { en: "I can meet you on Tuesday.", ua: "Я можу зустрітися з тобою у вівторок." },
      { en: "My week is full of tasks.", ua: "Мій тиждень повний завдань." },
      { en: "Saturday is perfect for rest.", ua: "Субота ідеальна для відпочинку." },
      { en: "Do you work on weekends?", ua: "Ти працюєш у вихідні?" },
      { en: "Let us make a plan.", ua: "Давай складемо план." },
    ],
    material: [
      "Урок 14. Дні тижня і плани",
      "[IMG:lesson-04-time.svg]",
      "Вступ: як говорити про свій розклад на тиждень.",
      "Міні-діалог:",
      "- Can we meet on Tuesday? (Можемо зустрітися у вівторок?)",
      "- Yes, Tuesday is good for me. (Так, вівторок мені підходить.)",
      "Теорія: дні тижня пишуться з великої літери.",
      "Граматика: from ... to ... / on Monday.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Я працюю з понеділка по п'ятницю.",
      expectedAnswers: ["i work from monday to friday"],
      explanationUa: "Використай шаблон from ... to ...",
    },
  },
  "Lesson 15": {
    words: [
      { en: "airport", ua: "аеропорт" }, { en: "flight", ua: "рейс" }, { en: "passport", ua: "паспорт" },
      { en: "luggage", ua: "багаж" }, { en: "gate", ua: "вихід на посадку" }, { en: "boarding", ua: "посадка" },
      { en: "arrival", ua: "прибуття" }, { en: "departure", ua: "виліт" }, { en: "customs", ua: "митниця" },
      { en: "security", ua: "контроль безпеки" }, { en: "delay", ua: "затримка" }, { en: "hotel", ua: "готель" },
    ],
    phrases: [
      { en: "Where is the check-in desk?", ua: "Де стійка реєстрації?" },
      { en: "My flight is at seven.", ua: "Мій рейс о сьомій." },
      { en: "I have only hand luggage.", ua: "У мене лише ручна поклажа." },
      { en: "Show your passport, please.", ua: "Покажіть ваш паспорт, будь ласка." },
      { en: "Boarding starts now.", ua: "Посадка починається зараз." },
      { en: "The flight is delayed.", ua: "Рейс затримується." },
      { en: "Where is gate number five?", ua: "Де вихід номер п'ять?" },
      { en: "I need a taxi to the hotel.", ua: "Мені потрібне таксі до готелю." },
      { en: "What time is arrival?", ua: "О котрій прибуття?" },
      { en: "Please go through security.", ua: "Будь ласка, пройдіть контроль безпеки." },
      { en: "Customs is this way.", ua: "Митниця в цьому напрямку." },
      { en: "My departure is tomorrow morning.", ua: "Мій виліт завтра зранку." },
      { en: "Can you help with my luggage?", ua: "Можете допомогти з моїм багажем?" },
      { en: "Have a good flight!", ua: "Гарного польоту!" },
    ],
    material: [
      "Урок 15. Подорож літаком",
      "[IMG:lesson-02-from.svg]",
      "Вступ: фрази для аеропорту і перельоту.",
      "Міні-діалог:",
      "- Where is gate number five? (Де вихід номер п'ять?)",
      "- It is after security control. (Він після контролю безпеки.)",
      "Теорія: travel vocabulary для поїздок.",
      "Граматика: теперішній і майбутній час у контексті розкладу.",
    ].join("\n"),
    step: {
      promptUa: "Переклади англійською: Мій рейс затримується. Де вихід номер п'ять?",
      expectedAnswers: ["my flight is delayed where is gate number five"],
      explanationUa: "Використай словник аеропорту у двох реченнях.",
    },
  },
});

const EXTENDED_LESSON_PACKS = Object.freeze([
  { id: "Lesson 16", title: "Урок 16. У готелі", image: "lesson-02-from.svg", topicUa: "бронювання та проживання", grammarUa: "Can I ... / I need ...", promptUa: "Переклади англійською: У мене бронювання. Мені потрібен ключ від номера." },
  { id: "Lesson 17", title: "Урок 17. У місті", image: "lesson-04-time.svg", topicUa: "орієнтування в місті", grammarUa: "Where is ...? / turn left-right", promptUa: "Переклади англійською: Де музей? Поверніть ліворуч на цій вулиці." },
  { id: "Lesson 18", title: "Урок 18. Телефонна розмова", image: "lesson-01-intro.svg", topicUa: "дзвінки і домовленості", grammarUa: "Can I speak to ...?", promptUa: "Переклади англійською: Можна поговорити з Анною? Передзвоніть пізніше." },
  { id: "Lesson 19", title: "Урок 19. У супермаркеті", image: "lesson-05-cafe.svg", topicUa: "продукти та оплата", grammarUa: "How much / How many", promptUa: "Переклади англійською: Скільки коштує молоко? Мені потрібні два яблука." },
  { id: "Lesson 20", title: "Урок 20. У подорожі", image: "lesson-02-from.svg", topicUa: "плани поїздки", grammarUa: "going to для намірів", promptUa: "Переклади англійською: Я збираюся відвідати Лондон. Я беру лише ручну поклажу." },
  { id: "Lesson 21", title: "Урок 21. Погода і одяг", image: "lesson-04-time.svg", topicUa: "одяг за погодою", grammarUa: "It is ... / wear", promptUa: "Переклади англійською: Сьогодні холодно. Одягни теплу куртку." },
  { id: "Lesson 22", title: "Урок 22. Здоров'я і спорт", image: "lesson-03-family.svg", topicUa: "здоровий спосіб життя", grammarUa: "should/should not", promptUa: "Переклади англійською: Тобі варто більше відпочивати. Пий більше води." },
  { id: "Lesson 23", title: "Урок 23. Робота в команді", image: "lesson-01-intro.svg", topicUa: "співпраця в команді", grammarUa: "let us / can we", promptUa: "Переклади англійською: Давай обговоримо проєкт. Можемо змінити план?" },
  { id: "Lesson 24", title: "Урок 24. Навчальна практика", image: "lesson-03-family.svg", topicUa: "повторення і помилки", grammarUa: "Past Simple базово", promptUa: "Переклади англійською: Я зробив помилку. Давай повторимо цю тему." },
  { id: "Lesson 25", title: "Урок 25. Вільний час", image: "lesson-01-intro.svg", topicUa: "хобі та відпочинок", grammarUa: "like/enjoy + gerund", promptUa: "Переклади англійською: Я люблю читати книги. Ми відпочиваємо у вихідні." },
  { id: "Lesson 26", title: "Урок 26. У ресторані", image: "lesson-05-cafe.svg", topicUa: "замовлення та сервіс", grammarUa: "I would like / could I", promptUa: "Переклади англійською: Я б хотів суп. Можна рахунок, будь ласка?" },
  { id: "Lesson 27", title: "Урок 27. У банку", image: "lesson-02-from.svg", topicUa: "фінансові операції", grammarUa: "need to / have to", promptUa: "Переклади англійською: Мені потрібно зняти гроші. Де найближчий банкомат?" },
  { id: "Lesson 28", title: "Урок 28. Онлайн-комунікація", image: "lesson-04-time.svg", topicUa: "листи та повідомлення", grammarUa: "can/could запити", promptUa: "Переклади англійською: Будь ласка, надішли мені лист. Можеш перевірити повідомлення?" },
  { id: "Lesson 29", title: "Урок 29. Плани на майбутнє", image: "lesson-04-time.svg", topicUa: "цілі та плани", grammarUa: "will / going to", promptUa: "Переклади англійською: Я буду вчити англійську щодня. Я збираюся подорожувати." },
  { id: "Lesson 30", title: "Урок 30. Підсумок", image: "lesson-01-intro.svg", topicUa: "закріплення курсу", grammarUa: "повторення ключових структур", promptUa: "Переклади англійською: Я готовий до розмови англійською. Дякую за уроки." },
]);

const LESSON_16_30_WORDS = Object.freeze({
  "Lesson 16": [{ en: "reservation", ua: "бронювання" }, { en: "reception", ua: "рецепція" }, { en: "room key", ua: "ключ від номера" }, { en: "check-in", ua: "заселення" }, { en: "check-out", ua: "виселення" }, { en: "guest", ua: "гість" }],
  "Lesson 17": [{ en: "museum", ua: "музей" }, { en: "crosswalk", ua: "пішохідний перехід" }, { en: "traffic light", ua: "світлофор" }, { en: "corner", ua: "кут" }, { en: "district", ua: "район" }, { en: "direction", ua: "напрямок" }],
  "Lesson 18": [{ en: "caller", ua: "той хто дзвонить" }, { en: "line", ua: "лінія" }, { en: "voicemail", ua: "голосова пошта" }, { en: "message", ua: "повідомлення" }, { en: "busy", ua: "зайнятий" }, { en: "appointment", ua: "домовленість" }],
  "Lesson 19": [{ en: "cart", ua: "візок" }, { en: "shelf", ua: "полиця" }, { en: "discount", ua: "знижка" }, { en: "cashier", ua: "касир" }, { en: "receipt", ua: "чек" }, { en: "checkout", ua: "каса" }],
  "Lesson 20": [{ en: "trip", ua: "подорож" }, { en: "itinerary", ua: "маршрут подорожі" }, { en: "destination", ua: "пункт призначення" }, { en: "currency", ua: "валюта" }, { en: "sightseeing", ua: "огляд пам'яток" }, { en: "souvenir", ua: "сувенір" }],
  "Lesson 21": [{ en: "forecast", ua: "прогноз" }, { en: "temperature", ua: "температура" }, { en: "raincoat", ua: "дощовик" }, { en: "umbrella", ua: "парасолька" }, { en: "scarf", ua: "шарф" }, { en: "gloves", ua: "рукавички" }],
  "Lesson 22": [{ en: "health", ua: "здоров'я" }, { en: "exercise", ua: "вправа" }, { en: "workout", ua: "тренування" }, { en: "energy", ua: "енергія" }, { en: "hydration", ua: "гідратація" }, { en: "routine", ua: "режим" }],
  "Lesson 23": [{ en: "team", ua: "команда" }, { en: "meeting", ua: "зустріч" }, { en: "deadline", ua: "дедлайн" }, { en: "priority", ua: "пріоритет" }, { en: "feedback", ua: "зворотний зв'язок" }, { en: "workflow", ua: "процес роботи" }],
  "Lesson 24": [{ en: "mistake", ua: "помилка" }, { en: "revision", ua: "повторення" }, { en: "rule", ua: "правило" }, { en: "attempt", ua: "спроба" }, { en: "correction", ua: "виправлення" }, { en: "progress", ua: "прогрес" }],
  "Lesson 25": [{ en: "hobby", ua: "хобі" }, { en: "reading", ua: "читання" }, { en: "cycling", ua: "велосипед" }, { en: "hiking", ua: "похід" }, { en: "concert", ua: "концерт" }, { en: "weekend", ua: "вихідні" }],
  "Lesson 26": [{ en: "menu", ua: "меню" }, { en: "starter", ua: "закуска" }, { en: "main course", ua: "основна страва" }, { en: "dessert", ua: "десерт" }, { en: "bill", ua: "рахунок" }, { en: "tip", ua: "чайові" }],
  "Lesson 27": [{ en: "account", ua: "рахунок" }, { en: "balance", ua: "баланс" }, { en: "withdraw", ua: "зняти" }, { en: "transfer", ua: "переказ" }, { en: "atm", ua: "банкомат" }, { en: "fee", ua: "комісія" }],
  "Lesson 28": [{ en: "email", ua: "електронний лист" }, { en: "attachment", ua: "вкладення" }, { en: "reply", ua: "відповідь" }, { en: "notification", ua: "сповіщення" }, { en: "link", ua: "посилання" }, { en: "password", ua: "пароль" }],
  "Lesson 29": [{ en: "goal", ua: "ціль" }, { en: "future", ua: "майбутнє" }, { en: "career", ua: "кар'єра" }, { en: "habit", ua: "звичка" }, { en: "challenge", ua: "виклик" }, { en: "motivation", ua: "мотивація" }],
  "Lesson 30": [{ en: "summary", ua: "підсумок" }, { en: "achievement", ua: "досягнення" }, { en: "confidence", ua: "впевненість" }, { en: "fluency", ua: "вільність мовлення" }, { en: "milestone", ua: "етап" }, { en: "next step", ua: "наступний крок" }],
});

const LESSON_16_30_PHRASES = Object.freeze({
  "Lesson 16": [{ en: "I have a reservation.", ua: "У мене є бронювання." }, { en: "Can I have a room key?", ua: "Можна ключ від номера?" }],
  "Lesson 17": [{ en: "Where is the museum?", ua: "Де музей?" }, { en: "Turn left at the traffic light.", ua: "Поверніть ліворуч на світлофорі." }],
  "Lesson 18": [{ en: "Can I speak to Anna?", ua: "Можна поговорити з Анною?" }, { en: "Please call back later.", ua: "Будь ласка, передзвоніть пізніше." }],
  "Lesson 19": [{ en: "How much is the milk?", ua: "Скільки коштує молоко?" }, { en: "I need two apples.", ua: "Мені потрібно два яблука." }],
  "Lesson 20": [{ en: "I am going to visit London.", ua: "Я збираюся відвідати Лондон." }, { en: "I take only hand luggage.", ua: "Я беру лише ручну поклажу." }],
  "Lesson 21": [{ en: "It is cold today.", ua: "Сьогодні холодно." }, { en: "Wear a warm jacket.", ua: "Одягни теплу куртку." }],
  "Lesson 22": [{ en: "You should rest more.", ua: "Тобі варто більше відпочивати." }, { en: "Drink more water.", ua: "Пий більше води." }],
  "Lesson 23": [{ en: "Let us discuss the project.", ua: "Давай обговоримо проєкт." }, { en: "Can we change the plan?", ua: "Можемо змінити план?" }],
  "Lesson 24": [{ en: "I made a mistake.", ua: "Я зробив помилку." }, { en: "Let us review this topic.", ua: "Давай повторимо цю тему." }],
  "Lesson 25": [{ en: "I like reading books.", ua: "Я люблю читати книги." }, { en: "We relax on weekends.", ua: "Ми відпочиваємо у вихідні." }],
  "Lesson 26": [{ en: "I would like soup.", ua: "Я б хотів суп." }, { en: "Could I have the bill, please?", ua: "Можна рахунок, будь ласка?" }],
  "Lesson 27": [{ en: "I need to withdraw money.", ua: "Мені потрібно зняти гроші." }, { en: "Where is the nearest ATM?", ua: "Де найближчий банкомат?" }],
  "Lesson 28": [{ en: "Please send me an email.", ua: "Будь ласка, надішли мені лист." }, { en: "Can you check the message?", ua: "Можеш перевірити повідомлення?" }],
  "Lesson 29": [{ en: "I will study English every day.", ua: "Я буду вчити англійську щодня." }, { en: "I am going to travel.", ua: "Я збираюся подорожувати." }],
  "Lesson 30": [{ en: "I am ready to speak English.", ua: "Я готовий говорити англійською." }, { en: "Thank you for the lessons.", ua: "Дякую за уроки." }],
});

const LESSON_16_30_WORD_EXPANSIONS = Object.freeze({
  "Lesson 16": [{ en: "lobby", ua: "лобі" }, { en: "porter", ua: "портьє" }, { en: "towel", ua: "рушник" }, { en: "service", ua: "сервіс" }, { en: "invoice", ua: "рахунок-фактура" }, { en: "late check-out", ua: "пізній виїзд" }],
  "Lesson 17": [{ en: "avenue", ua: "проспект" }, { en: "subway", ua: "підземка" }, { en: "bus stop", ua: "зупинка автобуса" }, { en: "landmark", ua: "орієнтир" }, { en: "pedestrian", ua: "пішохід" }, { en: "route", ua: "маршрут" }],
  "Lesson 18": [{ en: "ringtone", ua: "рингтон" }, { en: "missed call", ua: "пропущений дзвінок" }, { en: "conference call", ua: "конференц-дзвінок" }, { en: "operator", ua: "оператор" }, { en: "connection", ua: "з'єднання" }, { en: "callback", ua: "зворотний дзвінок" }],
  "Lesson 19": [{ en: "price tag", ua: "цінник" }, { en: "queue", ua: "черга" }, { en: "cash desk", ua: "каса" }, { en: "coupon", ua: "купон" }, { en: "package", ua: "упаковка" }, { en: "fresh", ua: "свіжий" }],
  "Lesson 20": [{ en: "boarding pass", ua: "посадковий талон" }, { en: "suitcase", ua: "валіза" }, { en: "platform number", ua: "номер платформи" }, { en: "journey", ua: "мандрівка" }, { en: "travel card", ua: "проїзний" }, { en: "booking", ua: "бронювання" }],
  "Lesson 21": [{ en: "drizzle", ua: "мряка" }, { en: "storm", ua: "буря" }, { en: "hood", ua: "капюшон" }, { en: "coat", ua: "пальто" }, { en: "sunlight", ua: "сонячне світло" }, { en: "chilly", ua: "прохолодно" }],
  "Lesson 22": [{ en: "gym", ua: "спортзал" }, { en: "trainer", ua: "тренер" }, { en: "pulse", ua: "пульс" }, { en: "diet", ua: "дієта" }, { en: "recovery", ua: "відновлення" }, { en: "wellness", ua: "добробут" }],
  "Lesson 23": [{ en: "agenda", ua: "порядок денний" }, { en: "minutes", ua: "протокол" }, { en: "milestone", ua: "етап" }, { en: "owner", ua: "відповідальний" }, { en: "handover", ua: "передача" }, { en: "status", ua: "статус" }],
  "Lesson 24": [{ en: "rewrite", ua: "переписати" }, { en: "clarify", ua: "уточнити" }, { en: "summary", ua: "підсумок" }, { en: "checkpoint", ua: "контрольна точка" }, { en: "revision card", ua: "картка повторення" }, { en: "pattern", ua: "шаблон" }],
  "Lesson 25": [{ en: "camping", ua: "кемпінг" }, { en: "photography", ua: "фотографія" }, { en: "painting", ua: "живопис" }, { en: "podcast", ua: "подкаст" }, { en: "weeknight", ua: "будній вечір" }, { en: "leisure", ua: "дозвілля" }],
  "Lesson 26": [{ en: "chef", ua: "шеф-кухар" }, { en: "special", ua: "фірмова страва" }, { en: "spicy", ua: "гострий" }, { en: "sweet", ua: "солодкий" }, { en: "reservation time", ua: "час бронювання" }, { en: "portion", ua: "порція" }],
  "Lesson 27": [{ en: "counter", ua: "стійка" }, { en: "loan", ua: "кредит" }, { en: "card limit", ua: "ліміт картки" }, { en: "security code", ua: "код безпеки" }, { en: "bank clerk", ua: "банківський працівник" }, { en: "approval", ua: "підтвердження" }],
  "Lesson 28": [{ en: "inbox", ua: "вхідні" }, { en: "spam", ua: "спам" }, { en: "thread", ua: "ланцюжок листів" }, { en: "draft", ua: "чернетка" }, { en: "username", ua: "ім'я користувача" }, { en: "login", ua: "вхід" }],
  "Lesson 29": [{ en: "target", ua: "ціль" }, { en: "roadmap", ua: "дорожня карта" }, { en: "discipline", ua: "дисципліна" }, { en: "consistency", ua: "послідовність" }, { en: "deadline", ua: "кінцевий термін" }, { en: "outcome", ua: "результат" }],
  "Lesson 30": [{ en: "review session", ua: "сесія повторення" }, { en: "speaking habit", ua: "звичка говоріння" }, { en: "self-check", ua: "самоперевірка" }, { en: "reflection", ua: "рефлексія" }, { en: "confidence boost", ua: "підсилення впевненості" }, { en: "next module", ua: "наступний модуль" }],
});

const LESSON_16_30_PHRASE_EXPANSIONS = Object.freeze({
  "Lesson 16": [{ en: "The reception is open all day.", ua: "Рецепція працює весь день." }, { en: "Could I get fresh towels, please?", ua: "Можна свіжі рушники, будь ласка?" }, { en: "I need late check-out tomorrow.", ua: "Мені потрібен пізній виїзд завтра." }],
  "Lesson 17": [{ en: "The bus stop is near the bridge.", ua: "Зупинка автобуса біля мосту." }, { en: "Use this route to the city center.", ua: "Використайте цей маршрут до центру." }, { en: "This landmark is easy to find.", ua: "Цей орієнтир легко знайти." }],
  "Lesson 18": [{ en: "I have a missed call from you.", ua: "У мене пропущений дзвінок від вас." }, { en: "The connection is bad right now.", ua: "Зараз погане з'єднання." }, { en: "Let us schedule a callback.", ua: "Давайте заплануємо зворотний дзвінок." }],
  "Lesson 19": [{ en: "Check the price tag on this item.", ua: "Перевірте цінник на цьому товарі." }, { en: "There is a long queue at the cash desk.", ua: "На касі довга черга." }, { en: "Do you have a coupon today?", ua: "У вас є купон сьогодні?" }],
  "Lesson 20": [{ en: "Please show your boarding pass.", ua: "Будь ласка, покажіть посадковий талон." }, { en: "My suitcase is very light.", ua: "Моя валіза дуже легка." }, { en: "What is the platform number?", ua: "Який номер платформи?" }],
  "Lesson 21": [{ en: "There is a light drizzle outside.", ua: "Надворі легка мряка." }, { en: "Take your coat and hood.", ua: "Візьми пальто і капюшон." }, { en: "It feels chilly this morning.", ua: "Сьогодні вранці прохолодно." }],
  "Lesson 22": [{ en: "I go to the gym three times a week.", ua: "Я ходжу в спортзал тричі на тиждень." }, { en: "Check your pulse after exercise.", ua: "Перевір свій пульс після вправ." }, { en: "Recovery is part of training.", ua: "Відновлення — частина тренувань." }],
  "Lesson 23": [{ en: "Please add this to the agenda.", ua: "Будь ласка, додай це в порядок денний." }, { en: "We need meeting minutes today.", ua: "Нам потрібен протокол зустрічі сьогодні." }, { en: "Who is the owner of this task?", ua: "Хто відповідальний за це завдання?" }],
  "Lesson 24": [{ en: "Rewrite this sentence one more time.", ua: "Перепиши це речення ще раз." }, { en: "Let us clarify this grammar pattern.", ua: "Давай уточнимо цей граматичний шаблон." }, { en: "Use a revision card for practice.", ua: "Використай картку повторення для практики." }],
  "Lesson 25": [{ en: "I listen to a podcast on weeknights.", ua: "Я слухаю подкаст у будні вечори." }, { en: "Photography is my favorite leisure activity.", ua: "Фотографія — моє улюблене дозвілля." }, { en: "We go camping in summer.", ua: "Ми їздимо в кемпінг влітку." }],
  "Lesson 26": [{ en: "The chef recommends today's special.", ua: "Шеф рекомендує фірмову страву дня." }, { en: "This dish is spicy but tasty.", ua: "Ця страва гостра, але смачна." }, { en: "Is this portion enough for two?", ua: "Цієї порції достатньо на двох?" }],
  "Lesson 27": [{ en: "Please wait at the counter.", ua: "Будь ласка, зачекайте біля стійки." }, { en: "Your card limit is updated now.", ua: "Ваш ліміт картки оновлено." }, { en: "We need manager approval first.", ua: "Нам спочатку потрібне підтвердження менеджера." }],
  "Lesson 28": [{ en: "I cannot find this email in my inbox.", ua: "Я не можу знайти цей лист у вхідних." }, { en: "Move this message to spam.", ua: "Перемісти це повідомлення в спам." }, { en: "Save the draft before logout.", ua: "Збережи чернетку перед виходом." }],
  "Lesson 29": [{ en: "Set one target for this week.", ua: "Постав одну ціль на цей тиждень." }, { en: "Follow your roadmap step by step.", ua: "Слідуй своїй дорожній карті крок за кроком." }, { en: "Consistency brings strong outcomes.", ua: "Послідовність приносить сильні результати." }],
  "Lesson 30": [{ en: "Do a short self-check every day.", ua: "Роби коротку самоперевірку щодня." }, { en: "Reflection helps you move forward.", ua: "Рефлексія допомагає рухатися далі." }, { en: "The next module starts tomorrow.", ua: "Наступний модуль починається завтра." }],
});

const LESSON_16_30_WORD_FINAL = Object.freeze({
  "Lesson 16": [{ en: "front desk", ua: "стійка реєстрації" }, { en: "booking code", ua: "код бронювання" }, { en: "key card", ua: "картка-ключ" }, { en: "room service", ua: "обслуговування номера" }, { en: "mini bar", ua: "мінібар" }, { en: "housekeeping", ua: "прибирання номера" }, { en: "blanket", ua: "ковдра" }, { en: "pillow", ua: "подушка" }],
  "Lesson 17": [{ en: "city hall", ua: "ратуша" }, { en: "station", ua: "станція" }, { en: "intersection", ua: "перехрестя" }, { en: "sidewalk", ua: "тротуар" }, { en: "underpass", ua: "підземний перехід" }, { en: "roundabout", ua: "кільце" }, { en: "lane", ua: "смуга руху" }, { en: "signpost", ua: "дорожній вказівник" }],
  "Lesson 18": [{ en: "dial", ua: "набрати номер" }, { en: "answer", ua: "відповісти" }, { en: "hold", ua: "утримання на лінії" }, { en: "extension", ua: "внутрішній номер" }, { en: "contact", ua: "контакт" }, { en: "voice note", ua: "голосове повідомлення" }, { en: "microphone", ua: "мікрофон" }, { en: "earpiece", ua: "навушник" }],
  "Lesson 19": [{ en: "aisle", ua: "прохід між полицями" }, { en: "counter", ua: "прилавок" }, { en: "barcode", ua: "штрихкод" }, { en: "promotion", ua: "акція" }, { en: "stock", ua: "запас товару" }, { en: "weigh", ua: "зважити" }, { en: "scan", ua: "сканувати" }, { en: "total", ua: "загальна сума" }],
  "Lesson 20": [{ en: "departure board", ua: "табло відправлень" }, { en: "arrival hall", ua: "зал прибуття" }, { en: "customs control", ua: "митний контроль" }, { en: "security check", ua: "перевірка безпеки" }, { en: "delay notice", ua: "повідомлення про затримку" }, { en: "transfer gate", ua: "вихід на пересадку" }, { en: "travel insurance", ua: "страхування подорожі" }, { en: "passport control", ua: "паспортний контроль" }],
  "Lesson 21": [{ en: "humidity", ua: "вологість" }, { en: "breeze", ua: "легкий вітер" }, { en: "downpour", ua: "злива" }, { en: "fog", ua: "туман" }, { en: "shade", ua: "тінь" }, { en: "sunburn", ua: "сонячний опік" }, { en: "warm up", ua: "зігрітися" }, { en: "cool down", ua: "охолодитися" }],
  "Lesson 22": [{ en: "stretching", ua: "розтяжка" }, { en: "cardio", ua: "кардіо" }, { en: "strength", ua: "сила" }, { en: "endurance", ua: "витривалість" }, { en: "meal plan", ua: "план харчування" }, { en: "calories", ua: "калорії" }, { en: "hydrated", ua: "зволожений" }, { en: "active", ua: "активний" }],
  "Lesson 23": [{ en: "assign", ua: "призначити" }, { en: "reviewer", ua: "рецензент" }, { en: "estimate", ua: "оцінка" }, { en: "blocker", ua: "блокер" }, { en: "sync", ua: "синхронізація" }, { en: "follow-up", ua: "подальші дії" }, { en: "priority queue", ua: "черга пріоритетів" }, { en: "delivery", ua: "поставка" }],
  "Lesson 24": [{ en: "retry", ua: "повторити спробу" }, { en: "score", ua: "оцінка" }, { en: "feedback note", ua: "нотатка з фідбеком" }, { en: "common error", ua: "типова помилка" }, { en: "example set", ua: "набір прикладів" }, { en: "revision plan", ua: "план повторення" }, { en: "grammar drill", ua: "граматичне тренування" }, { en: "checkpoint test", ua: "контрольний тест" }],
  "Lesson 25": [{ en: "playlist", ua: "плейлист" }, { en: "stream", ua: "трансляція" }, { en: "sketch", ua: "ескіз" }, { en: "journal", ua: "щоденник" }, { en: "community", ua: "спільнота" }, { en: "skill share", ua: "обмін навичками" }, { en: "week plan", ua: "план на тиждень" }, { en: "downtime", ua: "час відпочинку" }],
  "Lesson 26": [{ en: "appetizer", ua: "апетайзер" }, { en: "beverage", ua: "напій" }, { en: "vegetarian", ua: "вегетаріанський" }, { en: "grilled", ua: "на грилі" }, { en: "medium rare", ua: "середня прожарка" }, { en: "allergy", ua: "алергія" }, { en: "compliment", ua: "комплімент від закладу" }, { en: "reservation list", ua: "список бронювань" }],
  "Lesson 27": [{ en: "deposit slip", ua: "квитанція поповнення" }, { en: "withdrawal form", ua: "форма зняття" }, { en: "interest rate", ua: "відсоткова ставка" }, { en: "monthly fee", ua: "щомісячна комісія" }, { en: "verification", ua: "верифікація" }, { en: "identity check", ua: "перевірка особи" }, { en: "transaction", ua: "транзакція" }, { en: "receipt copy", ua: "копія квитанції" }],
  "Lesson 28": [{ en: "compose", ua: "написати лист" }, { en: "signature", ua: "підпис" }, { en: "unsubscribe", ua: "відписатися" }, { en: "security alert", ua: "сповіщення безпеки" }, { en: "two-factor", ua: "двофакторний" }, { en: "verification code", ua: "код підтвердження" }, { en: "shared link", ua: "спільне посилання" }, { en: "folder", ua: "папка" }],
  "Lesson 29": [{ en: "quarter", ua: "квартал року" }, { en: "objective", ua: "мета" }, { en: "timeline", ua: "таймлайн" }, { en: "commitment", ua: "зобов'язання" }, { en: "habit tracker", ua: "трекер звичок" }, { en: "focus", ua: "фокус" }, { en: "benchmark", ua: "орієнтир" }, { en: "long-term", ua: "довгостроковий" }],
  "Lesson 30": [{ en: "recap", ua: "короткий підсумок" }, { en: "review list", ua: "список повторення" }, { en: "speaking goal", ua: "ціль говоріння" }, { en: "practice streak", ua: "серія практики" }, { en: "confidence level", ua: "рівень впевненості" }, { en: "next objective", ua: "наступна ціль" }, { en: "learning path", ua: "навчальний шлях" }, { en: "final check", ua: "фінальна перевірка" }],
});

const LESSON_16_30_PHRASE_FINAL = Object.freeze({
  "Lesson 16": [{ en: "I booked a single room for three nights.", ua: "Я забронював одномісний номер на три ночі." }, { en: "Could you send housekeeping to my room?", ua: "Можете надіслати прибирання до мого номера?" }, { en: "The front desk is very helpful.", ua: "Стійка реєстрації дуже допомагає." }, { en: "I left my key card in the room.", ua: "Я залишив картку-ключ у номері." }, { en: "Please prepare the invoice for checkout.", ua: "Будь ласка, підготуйте рахунок на виїзд." }, { en: "Do you have room service at night?", ua: "У вас є обслуговування номера вночі?" }, { en: "Can I store my luggage in the lobby?", ua: "Можна залишити багаж у лобі?" }, { en: "I need an extra pillow, please.", ua: "Мені потрібна додаткова подушка, будь ласка." }, { en: "The booking code is in my email.", ua: "Код бронювання в моєму листі." }],
  "Lesson 17": [{ en: "Go straight until the next intersection.", ua: "Ідіть прямо до наступного перехрестя." }, { en: "The station is behind city hall.", ua: "Станція позаду ратуші." }, { en: "Use the underpass to cross safely.", ua: "Використайте підземний перехід для безпечного переходу." }, { en: "There is a signpost near the roundabout.", ua: "Біля кільця є дорожній вказівник." }, { en: "This sidewalk leads to the avenue.", ua: "Цей тротуар веде до проспекту." }, { en: "Take the right lane after the bridge.", ua: "Після мосту займіть праву смугу." }, { en: "The subway entrance is on your left.", ua: "Вхід у підземку ліворуч." }, { en: "Could you mark the route on my map?", ua: "Можете позначити маршрут на моїй мапі?" }, { en: "This district is popular with tourists.", ua: "Цей район популярний серед туристів." }],
  "Lesson 18": [{ en: "Please hold for a moment.", ua: "Будь ласка, зачекайте на лінії." }, { en: "I cannot answer right now.", ua: "Я не можу відповісти зараз." }, { en: "Dial the extension two zero five.", ua: "Наберіть внутрішній номер двісті п'ять." }, { en: "Send me a voice note later.", ua: "Надішли мені голосове повідомлення пізніше." }, { en: "Your microphone is muted.", ua: "Ваш мікрофон вимкнений." }, { en: "I saved your contact already.", ua: "Я вже зберіг ваш контакт." }, { en: "Can we switch to a conference call?", ua: "Можемо перейти на конференц-дзвінок?" }, { en: "I will answer after the meeting.", ua: "Я відповім після зустрічі." }, { en: "Please repeat, the signal is weak.", ua: "Повторіть, будь ласка, сигнал слабкий." }],
  "Lesson 19": [{ en: "This product is on promotion today.", ua: "Цей товар сьогодні по акції." }, { en: "Please weigh these apples for me.", ua: "Будь ласка, зважте ці яблука." }, { en: "The barcode is hard to scan.", ua: "Штрихкод важко сканується." }, { en: "The total is on the receipt.", ua: "Загальна сума вказана в чеку." }, { en: "There is no stock on this shelf.", ua: "На цій полиці немає запасу." }, { en: "I have a discount coupon.", ua: "У мене є знижковий купон." }, { en: "Can I pay cash at this counter?", ua: "Я можу заплатити готівкою на цьому прилавку?" }, { en: "The queue moves quickly here.", ua: "Черга тут рухається швидко." }, { en: "Please put this in one package.", ua: "Будь ласка, покладіть це в одну упаковку." }],
  "Lesson 20": [{ en: "The departure board shows a delay.", ua: "Табло відправлень показує затримку." }, { en: "We are waiting in the arrival hall.", ua: "Ми чекаємо в залі прибуття." }, { en: "Please pass passport control first.", ua: "Будь ласка, спочатку пройдіть паспортний контроль." }, { en: "My travel insurance is valid.", ua: "Моє страхування подорожі дійсне." }, { en: "The transfer gate changed again.", ua: "Вихід на пересадку знову змінили." }, { en: "Customs control is after security check.", ua: "Митний контроль після перевірки безпеки." }, { en: "I received a delay notice by email.", ua: "Я отримав повідомлення про затримку на email." }, { en: "Please keep your boarding pass ready.", ua: "Будь ласка, тримайте посадковий талон готовим." }, { en: "Where can I buy travel insurance?", ua: "Де можна купити страхування подорожі?" }],
  "Lesson 21": [{ en: "Humidity is high after the rain.", ua: "Вологість висока після дощу." }, { en: "A cold breeze comes from the river.", ua: "Холодний вітерець дме з річки." }, { en: "There may be a downpour tonight.", ua: "Сьогодні ввечері може бути злива." }, { en: "Fog makes the road hard to see.", ua: "Туман ускладнює видимість дороги." }, { en: "Stay in the shade at noon.", ua: "Будь у тіні опівдні." }, { en: "Do not get sunburn on the beach.", ua: "Не отримай сонячний опік на пляжі." }, { en: "I need to warm up my hands.", ua: "Мені треба зігріти руки." }, { en: "Open the window to cool down.", ua: "Відкрий вікно, щоб охолонути." }, { en: "The weather is mild this week.", ua: "Погода цього тижня м'яка." }],
  "Lesson 22": [{ en: "Cardio improves endurance quickly.", ua: "Кардіо швидко покращує витривалість." }, { en: "Stretching helps prevent injury.", ua: "Розтяжка допомагає уникнути травм." }, { en: "My meal plan is simple and healthy.", ua: "Мій план харчування простий і здоровий." }, { en: "Count calories only if needed.", ua: "Рахуй калорії лише за потреби." }, { en: "Stay hydrated during your workout.", ua: "Підтримуй водний баланс під час тренування." }, { en: "Strength training builds confidence.", ua: "Силові тренування будують впевненість." }, { en: "I try to be active every day.", ua: "Я намагаюся бути активним щодня." }, { en: "Recovery days are very important.", ua: "Дні відновлення дуже важливі." }, { en: "This routine works well for me.", ua: "Цей режим добре мені підходить." }],
  "Lesson 23": [{ en: "Let us assign an owner to this task.", ua: "Давай призначимо відповідального за це завдання." }, { en: "The reviewer left useful comments.", ua: "Рецензент залишив корисні коментарі." }, { en: "Our estimate was too optimistic.", ua: "Наша оцінка була занадто оптимістичною." }, { en: "This blocker affects delivery time.", ua: "Цей блокер впливає на термін доставки." }, { en: "We need a quick sync today.", ua: "Нам потрібна швидка синхронізація сьогодні." }, { en: "Please send a follow-up message.", ua: "Будь ласка, надішли повідомлення з подальшими діями." }, { en: "Put urgent items in priority queue.", ua: "Поклади термінові пункти у пріоритетну чергу." }, { en: "Delivery is planned for Friday.", ua: "Поставка запланована на п'ятницю." }, { en: "Current status is green.", ua: "Поточний статус — зелений." }],
  "Lesson 24": [{ en: "Retry this exercise with a timer.", ua: "Повтори цю вправу з таймером." }, { en: "Your score improved this week.", ua: "Твоя оцінка покращилася цього тижня." }, { en: "Read the feedback note carefully.", ua: "Уважно прочитай нотатку з фідбеком." }, { en: "This is a common error in tense use.", ua: "Це типова помилка у вживанні часу." }, { en: "Use the example set for revision.", ua: "Використай набір прикладів для повторення." }, { en: "Create a short revision plan.", ua: "Створи короткий план повторення." }, { en: "Do one grammar drill every day.", ua: "Роби одне граматичне тренування щодня." }, { en: "Take a checkpoint test on Sunday.", ua: "Пройди контрольний тест у неділю." }, { en: "Your progress is stable now.", ua: "Твій прогрес зараз стабільний." }],
  "Lesson 25": [{ en: "I update my playlist every week.", ua: "Я оновлюю свій плейлист щотижня." }, { en: "We watch a live stream together.", ua: "Ми дивимося пряму трансляцію разом." }, { en: "I made a quick sketch in my journal.", ua: "Я зробив швидкий ескіз у щоденнику." }, { en: "Our community shares useful ideas.", ua: "Наша спільнота ділиться корисними ідеями." }, { en: "Skill share events are fun.", ua: "Події з обміну навичками — цікаві." }, { en: "I keep a small week plan.", ua: "Я веду невеликий план на тиждень." }, { en: "Downtime helps me reset my mind.", ua: "Час відпочинку допомагає перезавантажити думки." }, { en: "Photography is part of my hobby.", ua: "Фотографія — частина мого хобі." }, { en: "I paint when I need calm.", ua: "Я малюю, коли мені потрібен спокій." }],
  "Lesson 26": [{ en: "I would like a light appetizer.", ua: "Я б хотів легку закуску." }, { en: "What beverage do you recommend?", ua: "Який напій ви рекомендуєте?" }, { en: "Do you have vegetarian options?", ua: "У вас є вегетаріанські опції?" }, { en: "I prefer grilled vegetables.", ua: "Я віддаю перевагу овочам на грилі." }, { en: "Can I order medium rare steak?", ua: "Можна замовити стейк середньої прожарки?" }, { en: "Please note my allergy.", ua: "Будь ласка, врахуйте мою алергію." }, { en: "We got a compliment from the chef.", ua: "Ми отримали комплімент від шефа." }, { en: "Check the reservation list, please.", ua: "Перевірте список бронювань, будь ласка." }, { en: "This portion is perfect for me.", ua: "Ця порція ідеальна для мене." }],
  "Lesson 27": [{ en: "Fill in the deposit slip here.", ua: "Заповніть квитанцію поповнення тут." }, { en: "I need a withdrawal form.", ua: "Мені потрібна форма зняття." }, { en: "What is your interest rate?", ua: "Яка у вас відсоткова ставка?" }, { en: "Is there a monthly fee?", ua: "Є щомісячна комісія?" }, { en: "Please complete identity check.", ua: "Будь ласка, пройдіть перевірку особи." }, { en: "Your transaction is successful.", ua: "Ваша транзакція успішна." }, { en: "Can I get a receipt copy?", ua: "Можна копію квитанції?" }, { en: "Verification may take five minutes.", ua: "Верифікація може зайняти п'ять хвилин." }, { en: "This bank clerk is very polite.", ua: "Цей банківський працівник дуже ввічливий." }],
  "Lesson 28": [{ en: "Compose a short reply to this email.", ua: "Склади коротку відповідь на цей лист." }, { en: "Add your signature at the end.", ua: "Додай свій підпис у кінці." }, { en: "Click unsubscribe for newsletters.", ua: "Натисни відписатися для розсилок." }, { en: "I got a security alert this morning.", ua: "Я отримав сповіщення безпеки сьогодні вранці." }, { en: "Enable two-factor login today.", ua: "Увімкни двофакторний вхід сьогодні." }, { en: "Enter the verification code now.", ua: "Введи код підтвердження зараз." }, { en: "Send me the shared link again.", ua: "Надішли мені спільне посилання ще раз." }, { en: "Move this mail to a folder.", ua: "Перемісти цей лист у папку." }, { en: "My inbox is finally clean.", ua: "Мої вхідні нарешті чисті." }],
  "Lesson 29": [{ en: "Set one objective for each quarter.", ua: "Постав одну мету на кожен квартал." }, { en: "Create a realistic timeline.", ua: "Створи реалістичний таймлайн." }, { en: "Keep your commitment every day.", ua: "Тримай своє зобов'язання щодня." }, { en: "Use a habit tracker for progress.", ua: "Використовуй трекер звичок для прогресу." }, { en: "Stay focused on one target.", ua: "Тримай фокус на одній цілі." }, { en: "This benchmark is achievable.", ua: "Цей орієнтир досяжний." }, { en: "Think long-term and act today.", ua: "Думай довгостроково і дій сьогодні." }, { en: "Discipline beats motivation sometimes.", ua: "Дисципліна інколи сильніша за мотивацію." }, { en: "Review outcomes every Friday.", ua: "Переглядай результати щоп'ятниці." }],
  "Lesson 30": [{ en: "Write a short recap after each lesson.", ua: "Пиши короткий підсумок після кожного уроку." }, { en: "Use your review list on weekends.", ua: "Використовуй список повторення у вихідні." }, { en: "Set one speaking goal per week.", ua: "Став одну ціль говоріння на тиждень." }, { en: "Keep your practice streak alive.", ua: "Підтримуй серію практики." }, { en: "Track your confidence level monthly.", ua: "Відстежуй рівень впевненості щомісяця." }, { en: "Define your next objective clearly.", ua: "Чітко визнач свою наступну ціль." }, { en: "Follow a simple learning path.", ua: "Слідуй простому навчальному шляху." }, { en: "Do a final check before speaking.", ua: "Зроби фінальну перевірку перед розмовою." }, { en: "You are ready for the next module.", ua: "Ти готовий до наступного модуля." }],
});

function createExtendedLessonOverrides() {
  const overrides = {};
  EXTENDED_LESSON_PACKS.forEach((pack, index) => {
    const baseWordsSeed = LESSON_16_30_WORDS[pack.id] ?? [
      { en: "lesson", ua: "урок" }, { en: "topic", ua: "тема" }, { en: "dialogue", ua: "діалог" },
      { en: "question", ua: "питання" }, { en: "answer", ua: "відповідь" }, { en: "practice", ua: "практика" },
      { en: "example", ua: "приклад" }, { en: "grammar", ua: "граматика" }, { en: "vocabulary", ua: "словник" },
      { en: "phrase", ua: "фраза" }, { en: "review", ua: "повторення" }, { en: "result", ua: "результат" },
    ];
    const basePhrasesSeed = LESSON_16_30_PHRASES[pack.id] ?? [
      { en: `This is ${pack.id.toLowerCase()}.`, ua: `Це ${pack.id.toLowerCase()}.` },
      { en: "Let us start with a short dialogue.", ua: "Давай почнемо з короткого діалогу." },
      { en: `Topic: ${pack.topicUa}.`, ua: `Тема: ${pack.topicUa}.` },
      { en: "Please repeat the key phrases.", ua: "Будь ласка, повтори ключові фрази." },
      { en: "Can you answer this question?", ua: "Можеш відповісти на це питання?" },
      { en: "This grammar rule is important.", ua: "Це граматичне правило важливе." },
      { en: "Let us do one more exercise.", ua: "Давай зробимо ще одну вправу." },
      { en: "Your progress is getting better.", ua: "Твій прогрес стає кращим." },
      { en: "We will review this topic tomorrow.", ua: "Ми повторимо цю тему завтра." },
      { en: "Great job, keep practicing.", ua: "Чудова робота, продовжуй практикуватися." },
    ];
    const expandedWordsSeed = [
      ...baseWordsSeed,
      ...(LESSON_16_30_WORD_EXPANSIONS[pack.id] ?? []),
      ...(LESSON_16_30_WORD_FINAL[pack.id] ?? []),
    ];
    const expandedPhrasesSeed = [
      ...basePhrasesSeed,
      ...(LESSON_16_30_PHRASE_EXPANSIONS[pack.id] ?? []),
      ...(LESSON_16_30_PHRASE_FINAL[pack.id] ?? []),
    ];
    overrides[pack.id] = {
      words: expandedWordsSeed.slice(0, WORDS_PER_THEME),
      phrases: expandedPhrasesSeed.slice(0, 14),
      material: [
        pack.title,
        `[IMG:${pack.image}]`,
        `Вступ: ${pack.topicUa}.`,
        "Міні-діалог:",
        "- Let us start this lesson. (Давай почнемо цей урок.)",
        "- Yes, I am ready. (Так, я готовий.)",
        "Теорія: працюємо з короткими практичними фразами.",
        `Граматика: ${pack.grammarUa}.`,
      ].join("\n"),
      step: {
        promptUa: pack.promptUa,
        expectedAnswers: [expandedPhrasesSeed.slice(0, 2).map((item) => item.en.replace(/[.?!]/g, "")).join(" ").toLowerCase()],
        explanationUa: "Сформуй просту відповідь у форматі I am ...",
      },
    };
  });
  return Object.freeze(overrides);
}

const LESSON_OVERRIDES = Object.freeze({
  ...EARLY_LESSON_OVERRIDES,
  ...createExtendedLessonOverrides(),
});

function fillLessonWords(words, themeName) {
  const result = [...words].slice(0, WORDS_PER_THEME);
  const lessonSeed = Math.max(0, THEME_NAMES.indexOf(themeName));
  let counter = 1;
  while (result.length < WORDS_PER_THEME) {
    const fallbackWord = COMMON_WORD_POOL[(lessonSeed * 11 + counter) % COMMON_WORD_POOL.length];
    result.push({ en: fallbackWord.en, ua: fallbackWord.ua });
    counter += 1;
  }
  return result;
}

function fillLessonPhrases(phrases, themeName, phrasesPerTheme) {
  const result = [...phrases].slice(0, phrasesPerTheme);
  const lessonSeed = Math.max(0, THEME_NAMES.indexOf(themeName));
  let counter = 1;
  while (result.length < phrasesPerTheme) {
    const fallbackPhrase = COMMON_PHRASE_POOL[(lessonSeed * 13 + counter) % COMMON_PHRASE_POOL.length];
    result.push({ en: fallbackPhrase.en, ua: fallbackPhrase.ua });
    counter += 1;
  }
  return result;
}

function createDefaultLessonMaterial(themeName) {
  return [
    `Тема уроку: ${themeName}`,
    "[IMG:lesson-05-cafe.svg]",
    "Вступ: короткий діалог і ключові фрази для щоденного спілкування.",
    "Теорія: зверни увагу на порядок слів у реченні (підмет -> присудок -> додаток).",
    "Граматика: повтори базові конструкції Present Simple (I/You/We + verb).",
    "План уроку:",
    "1) Словник (EN-UA).",
    "2) Тест словника (UA-EN / EN-UA).",
    "3) Фрази та тест фраз.",
    "4) Основна вправа уроку.",
  ].join("\n");
}

function createProjectIntros() {
  const intros = {};
  THEME_NAMES.forEach((themeName, themeIndex) => {
    const phrasesPerTheme = BASE_PHRASES_PER_THEME + (themeIndex < EXTRA_PHRASES_THEMES ? 1 : 0);
    const override = LESSON_OVERRIDES[themeName];
    if (override) {
      intros[themeName] = {
        words: fillLessonWords(override.words, themeName),
        phrases: fillLessonPhrases(override.phrases, themeName, phrasesPerTheme),
        themeOrder: themeIndex + 1,
      };
      return;
    }
    intros[themeName] = {
      words: fillLessonWords([], themeName),
      phrases: fillLessonPhrases([], themeName, phrasesPerTheme),
      themeOrder: themeIndex + 1,
    };
  });
  return intros;
}

export const PROJECT_INTROS = Object.freeze(createProjectIntros());

export const LESSON_STEPS = Object.freeze(
  THEME_NAMES.map((themeName, index) => ({
    id: `step_${index + 1}`,
    type: "translate_ua_to_en",
    project: themeName,
    promptUa: LESSON_OVERRIDES[themeName]?.step?.promptUa
      ?? `Переклади англійською фразу теми ${themeName}: ${themeName} phrase 01.`,
    expectedAnswers: LESSON_OVERRIDES[themeName]?.step?.expectedAnswers
      ?? [`${themeName.toLowerCase()} phrase 01`],
    explanationUa: LESSON_OVERRIDES[themeName]?.step?.explanationUa
      ?? `Базова вправа для теми ${themeName}.`,
  })),
);

export const LESSON_MATERIALS = Object.freeze(
  THEME_NAMES.reduce((accumulator, themeName) => {
    accumulator[themeName] = LESSON_OVERRIDES[themeName]?.material ?? createDefaultLessonMaterial(themeName);
    return accumulator;
  }, {}),
);

export const EN_UA_GLOSSARY = Object.freeze({
  "hello": "привіт",
  "hi": "привіт",
  "my name is": "мене звати",
  "i am": "я є",
  "i'm": "я є",
  "how are you": "як справи",
  "nice to meet you": "приємно познайомитися",
  "english": "англійська",
  "phrase": "фраза",
  "word": "слово",
  "learn": "вчити",
  "study": "вивчати",
  "good": "добре",
  "fine": "добре",
  "where are you from": "звідки ти",
  "i am from": "я з",
  "i live in": "я живу в",
  "i would like": "я б хотів",
  "can i have": "можна мені",
  "menu": "меню",
  "bill": "рахунок",
});

